---
- hosts: test_machine
  become: yes

  pre_tasks:
  - apt:
      name: python-docker
      update_cache: yes

  post_tasks:
  - apt:
      name: python-docker
      state: absent
      purge: yes

  roles:
  - role: '.'
    netatalk_version: 3.1.11
    config_volume: /srv/docker/netatalk/config
    data_volume: /srv/docker/netatalk/data
    log_volume: /var/log/netatalk
    afp_tcp_port: 548
    ldap_tcp_port: 636
    accounts:
    - username: bs
      password: bs@password
      name: bs@afp
      size_limit: 60000
