---
- name: create config directory
  file: path={{config_volume}} state=directory owner=root group=root mode=0755
  when: not(
            (config_volume is undefined)
            or
            (config_volume is none)
            or
            (config_volume | trim == '')
          )

- name: create data directory
  file: path={{data_volume}} state=directory owner=root group=root mode=0755
  when: not(
            (data_volume is undefined)
            or
            (data_volume is none)
            or
            (data_volume | trim == '')
          )

- name: create log directory
  file: path={{log_volume}} state=directory owner=root group=root mode=0755
  when: not(
            (log_volume is undefined)
            or
            (log_volume is none)
            or
            (log_volume | trim == '')
          )
